version: "3"
services:
  mysql:
    image: mysql:8.0
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      - MYSQL_DATABASE=${DOCKER_MYSQL_DB_NAME}
      - MYSQL_USER=${DOCKER_MYSQL_USER}
      - MYSQL_PASSWORD=${DOCKER_MYSQL_PASS}
      - MYSQL_ROOT_PASSWORD=${DOCKER_MYSQL_PASS}
    ports:
    - ${DOCKER_MYSQL_PORT}:3306
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DOCKER_MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DOCKER_MONGO_PASS}
    ports:
      - ${DOCKER_MONGO_PORT}:27017
  firestore:
    image: mtlynch/firestore-emulator
    environment:
      - FIRESTORE_PROJECT_ID=dummy-project-id
      - PORT=8200
    ports:
      - 8200:8200

