name: CI/CD

on:
  push:
    branches:
      - main

# https://github.com/google-github-actions/setup-gcloud/blob/main/example-workflows/cloud-run/README.md
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18.6.0"
      - name: Generate .env file from Github Secrets
        run: echo "${{ secrets.APP_ENV_FILE }}" > .env
      - name: Install NPM dependencies
        run: yarn
      - name: Build
        run: yarn build
      # - name: ESLint
      #   run: yarn lint

  cd:
    needs: ci
    runs-on: ubuntu-latest
    # Add "id-token" with the intended permissions.
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      ###################
      # Cloud Functions #
      ###################
      - name: Checkout
        uses: actions/checkout@v4
      # - name: Generate .env.yaml file from Github Secrets
      #   run: echo "${{ secrets.APP_ENV_YAML }}" > .env.yaml

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS_JSON }}'

      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloud-functions@v1'
        with:
          name: 'pomodoro-api'
          runtime: 'nodejs18'
          # env_vars_file: .env.yaml