name: CI/CD

on:
  push:
    branches:
      - main

# https://github.com/google-github-actions/setup-gcloud/blob/main/example-workflows/cloud-run/README.md
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18.6.0"
      - name: Install NPM dependencies
        run: yarn
      - name: Build
        run: yarn build
      # - name: ESLint
      #   run: yarn lint

  cd:
    needs: ci
    runs-on: ubuntu-latest
    # Add "id-token" with the intended permissions.
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      ###################
      # Cloud Functions #
      ###################
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate .env.yml file from Github Secrets
        run: echo "${{ secrets.APP_ENV_YAML }}" > .env.yml
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS_JSON }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 416.0.0'

      - name: 'deploy'
        run: gcloud functions deploy pomodoro-api --entry-point pomodoroBack --runtime nodejs18 --region=asia-northeast1 --env-vars-file=.env.yml --trigger-http